#!/bin/bash
set -e
eval "$($(dirname $0)/retro-config)"
cmd=$retro_tools_dir/retro-$1

if [ -x $cmd ]
then
  $cmd
else
  echo "usage: retro COMMAND [ARG] ..."
  echo "COMMAND is one of:"
  echo "  init"
  echo "  add"
  echo "  latest"
  echo "  config"
fi

