#!/bin/bash
set -e

eval "$($(dirname $0)/retro-config)"
retro_dir=$("$retro_tools_dir/_retro_dir")

if ! [ -x "$(command -v tac)" ]; then
  tac() {
    tail -r "$@"
  }
fi

exec 3>&2
exec 2> /dev/null

last_retro=$(find "$retro_dir"  -mindepth 3 -name '*.md' | grep -E "\/[0-9]{4}\/[0-9]{2}\/[0-9]{2}\.md" | sort | tail -1)

exec 2>&3

if [ -z $last_retro ]; then
  echo ERROR: no retros available, try \`retro add\`
  exit 1
fi
tac "$last_retro" | awk '/^# / {print ; exit} 1' | tac
