#!/bin/bash
set -e

retro_tools_dir=$(dirname $0)
retro_dir=doc/retro
template=$retro_tools_dir/template.md
date=${retro_date:-$(date +%Y-%m-%d)}
year=${date:0:4}
month=${date:5:2}
day=${date:8:2}

target_dir=$retro_dir/$year/$month
target_file=$target_dir/$day.md

mkdir -p $target_dir
echo "# $date" > $target_file
cat $template >> $target_file
$EDITOR $target_file
echo $target_file
