#!/bin/bash
set -e

eval "$($(dirname $0)/retro-config)"
retro_dir=$("$retro_tools_dir/_retro_dir")

if [ -f doc/retro/template.md ]; then
  template=doc/retro/template.md
else
  template=$retro_tools_dir/template.md
fi

date=${retro_date:-$(date +%Y-%m-%d)}
year=${date:0:4}
month=${date:5:2}
day=${date:8:2}

target_dir=$retro_dir/$year/$month
target_file=$target_dir/$day.md

mkdir -p $target_dir
if [ ! -f $target_file ]; then
  echo "# $date" > $target_file
else
  echo "---" >> $target_file
fi
cat $template >> $target_file

$retro_editor $target_file
echo $target_file
