#!/bin/bash
set -e

eval "$($(dirname $0)/retro-config)"
retro_dir=$("$retro_tools_dir/_retro_dir")
readme="$retro_dir/README.md"

mkdir -p $retro_dir
if [ ! -f $readme ]; then
  cp $retro_tools_dir/README.md $readme
  echo $readme
else
  echo "You've already set up a retro folder!"
fi
